# Minimal cargo-deny configuration for CI/CD

[licenses]
confidence-threshold = 0.6
allow = [
    "MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-3.0", 
    "CC0-1.0", "0BSD", "Zlib", "BSL-1.0", "MPL-2.0",
    "CDLA-Permissive-2.0",  # Community Data License Agreement
]

[advisories]
ignore = [
    "RUSTSEC-2023-0071", "RUSTSEC-2024-0384", "RUSTSEC-2024-0436",
]

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "allow"
unknown-git = "allow"