# Comprehensive cargo-deny configuration for Paradigm Network
# This is the main configuration file that cargo-deny looks for by default

[licenses]
# Allow common OSI/FSF approved licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSD-3-Clause-Clear",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016", 
    "CC0-1.0",
    "0BSD",
    "Zlib",
    "BSL-1.0",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
    "OFL-1.1", # SIL Open Font License
    "WTFPL", # Do What The F*ck You Want To Public License
]

# Allow licenses with lower confidence threshold
confidence-threshold = 0.6

# Specific exceptions for dual-licensed and special case crates
exceptions = [
    # Allow all standard dual-licensed crates with Apache-2.0 OR MIT
    { allow = ["Apache-2.0", "MIT"], name = "addr2line" },
    { allow = ["Apache-2.0", "MIT"], name = "adler" },
    { allow = ["Apache-2.0", "MIT"], name = "adler2" },
    { allow = ["Apache-2.0", "MIT"], name = "aho-corasick" },
    { allow = ["Apache-2.0", "MIT"], name = "autocfg" },
    { allow = ["Apache-2.0", "MIT"], name = "backtrace" },
    { allow = ["Apache-2.0", "MIT"], name = "base64" },
    { allow = ["Apache-2.0", "MIT"], name = "bitflags" },
    { allow = ["Apache-2.0", "MIT"], name = "bstr" },
    { allow = ["Apache-2.0", "MIT"], name = "byteorder" },
    { allow = ["Apache-2.0", "MIT"], name = "bytes" },
    { allow = ["Apache-2.0", "MIT"], name = "cfg-if" },
    { allow = ["Apache-2.0", "MIT"], name = "crossbeam-channel" },
    { allow = ["Apache-2.0", "MIT"], name = "crossbeam-deque" },
    { allow = ["Apache-2.0", "MIT"], name = "crossbeam-epoch" },
    { allow = ["Apache-2.0", "MIT"], name = "crossbeam-utils" },
    { allow = ["Apache-2.0", "MIT"], name = "crc32fast" },
    { allow = ["Apache-2.0", "MIT"], name = "encoding_rs" },
    { allow = ["Apache-2.0", "MIT"], name = "fastrand" },
    { allow = ["Apache-2.0", "MIT"], name = "flate2" },
    { allow = ["Apache-2.0", "MIT"], name = "fnv" },
    { allow = ["Apache-2.0", "MIT"], name = "form_urlencoded" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-channel" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-core" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-io" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-sink" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-task" },
    { allow = ["Apache-2.0", "MIT"], name = "futures-util" },
    { allow = ["Apache-2.0", "MIT"], name = "getrandom" },
    { allow = ["Apache-2.0", "MIT"], name = "gimli" },
    { allow = ["Apache-2.0", "MIT"], name = "h2" },
    { allow = ["Apache-2.0", "MIT"], name = "hashbrown" },
    { allow = ["Apache-2.0", "MIT"], name = "hermit-abi" },
    { allow = ["Apache-2.0", "MIT"], name = "http" },
    { allow = ["Apache-2.0", "MIT"], name = "http-body" },
    { allow = ["Apache-2.0", "MIT"], name = "httparse" },
    { allow = ["Apache-2.0", "MIT"], name = "httpdate" },
    { allow = ["Apache-2.0", "MIT"], name = "hyper" },
    { allow = ["Apache-2.0", "MIT"], name = "hyper-tls" },
    { allow = ["Apache-2.0", "MIT"], name = "idna" },
    { allow = ["Apache-2.0", "MIT"], name = "indexmap" },
    { allow = ["Apache-2.0", "MIT"], name = "ipnet" },
    { allow = ["Apache-2.0", "MIT"], name = "itoa" },
    { allow = ["Apache-2.0", "MIT"], name = "js-sys" },
    { allow = ["Apache-2.0", "MIT"], name = "libc" },
    { allow = ["Apache-2.0", "MIT"], name = "lock_api" },
    { allow = ["Apache-2.0", "MIT"], name = "log" },
    { allow = ["Apache-2.0", "MIT"], name = "memchr" },
    { allow = ["Apache-2.0", "MIT"], name = "memmap2" },
    { allow = ["Apache-2.0", "MIT"], name = "mime" },
    { allow = ["Apache-2.0", "MIT"], name = "miniz_oxide" },
    { allow = ["Apache-2.0", "MIT"], name = "mio" },
    { allow = ["Apache-2.0", "MIT"], name = "native-tls" },
    { allow = ["Apache-2.0", "MIT"], name = "num-bigint" },
    { allow = ["Apache-2.0", "MIT"], name = "num-integer" },
    { allow = ["Apache-2.0", "MIT"], name = "num-traits" },
    { allow = ["Apache-2.0", "MIT"], name = "object" },
    { allow = ["Apache-2.0", "MIT"], name = "once_cell" },
    { allow = ["Apache-2.0", "MIT"], name = "parking_lot" },
    { allow = ["Apache-2.0", "MIT"], name = "parking_lot_core" },
    { allow = ["Apache-2.0", "MIT"], name = "percent-encoding" },
    { allow = ["Apache-2.0", "MIT"], name = "pin-project" },
    { allow = ["Apache-2.0", "MIT"], name = "pin-project-internal" },
    { allow = ["Apache-2.0", "MIT"], name = "pin-project-lite" },
    { allow = ["Apache-2.0", "MIT"], name = "pin-utils" },
    { allow = ["Apache-2.0", "MIT"], name = "proc-macro2" },
    { allow = ["Apache-2.0", "MIT"], name = "quote" },
    { allow = ["Apache-2.0", "MIT"], name = "rand" },
    { allow = ["Apache-2.0", "MIT"], name = "rand_chacha" },
    { allow = ["Apache-2.0", "MIT"], name = "rand_core" },
    { allow = ["Apache-2.0", "MIT"], name = "rayon" },
    { allow = ["Apache-2.0", "MIT"], name = "rayon-core" },
    { allow = ["Apache-2.0", "MIT"], name = "regex" },
    { allow = ["Apache-2.0", "MIT"], name = "regex-automata" },
    { allow = ["Apache-2.0", "MIT"], name = "regex-syntax" },
    { allow = ["Apache-2.0", "MIT"], name = "reqwest" },
    { allow = ["Apache-2.0", "MIT"], name = "rustc-demangle" },
    { allow = ["Apache-2.0", "MIT"], name = "rustix" },
    { allow = ["Apache-2.0", "MIT"], name = "ryu" },
    { allow = ["Apache-2.0", "MIT"], name = "scopeguard" },
    { allow = ["Apache-2.0", "MIT"], name = "serde" },
    { allow = ["Apache-2.0", "MIT"], name = "serde_derive" },
    { allow = ["Apache-2.0", "MIT"], name = "serde_json" },
    { allow = ["Apache-2.0", "MIT"], name = "serde_urlencoded" },
    { allow = ["Apache-2.0", "MIT"], name = "sha1" },
    { allow = ["Apache-2.0", "MIT"], name = "sha2" },
    { allow = ["Apache-2.0", "MIT"], name = "slab" },
    { allow = ["Apache-2.0", "MIT"], name = "smallvec" },
    { allow = ["Apache-2.0", "MIT"], name = "socket2" },
    { allow = ["Apache-2.0", "MIT"], name = "syn" },
    { allow = ["Apache-2.0", "MIT"], name = "tempfile" },
    { allow = ["Apache-2.0", "MIT"], name = "thiserror" },
    { allow = ["Apache-2.0", "MIT"], name = "thiserror-impl" },
    { allow = ["Apache-2.0", "MIT"], name = "tinyvec" },
    { allow = ["Apache-2.0", "MIT"], name = "tinyvec_macros" },
    { allow = ["Apache-2.0", "MIT"], name = "tokio" },
    { allow = ["Apache-2.0", "MIT"], name = "tokio-native-tls" },
    { allow = ["Apache-2.0", "MIT"], name = "tokio-rustls" },
    { allow = ["Apache-2.0", "MIT"], name = "tokio-stream" },
    { allow = ["Apache-2.0", "MIT"], name = "tokio-util" },
    { allow = ["Apache-2.0", "MIT"], name = "tower" },
    { allow = ["Apache-2.0", "MIT"], name = "tower-layer" },
    { allow = ["Apache-2.0", "MIT"], name = "tower-service" },
    { allow = ["Apache-2.0", "MIT"], name = "tracing" },
    { allow = ["Apache-2.0", "MIT"], name = "tracing-core" },
    { allow = ["Apache-2.0", "MIT"], name = "try-lock" },
    { allow = ["Apache-2.0", "MIT"], name = "unicode-bidi" },
    { allow = ["Apache-2.0", "MIT"], name = "unicode-ident" },
    { allow = ["Apache-2.0", "MIT"], name = "unicode-normalization" },
    { allow = ["Apache-2.0", "MIT"], name = "url" },
    { allow = ["Apache-2.0", "MIT"], name = "uuid" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen-backend" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen-futures" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen-macro" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen-macro-support" },
    { allow = ["Apache-2.0", "MIT"], name = "wasm-bindgen-shared" },
    { allow = ["Apache-2.0", "MIT"], name = "web-sys" },
    { allow = ["Apache-2.0", "MIT"], name = "webpki-roots" },
    { allow = ["Apache-2.0", "MIT"], name = "winapi" },
    { allow = ["Apache-2.0", "MIT"], name = "winapi-i686-pc-windows-gnu" },
    { allow = ["Apache-2.0", "MIT"], name = "winapi-x86_64-pc-windows-gnu" },
    { allow = ["Apache-2.0", "MIT"], name = "windows" },
    { allow = ["Apache-2.0", "MIT"], name = "windows-core" },
    { allow = ["Apache-2.0", "MIT"], name = "windows-sys" },
    { allow = ["Apache-2.0", "MIT"], name = "windows-targets" },
    { allow = ["Apache-2.0", "MIT"], name = "yamux" },
]

[advisories]
# Ignore unmaintained crates that are used transitively and have no safe alternatives
ignore = [
    "RUSTSEC-2023-0071",  # RSA Marvin Attack - no fix available yet
    "RUSTSEC-2024-0384",  # instant crate unmaintained - used by libp2p ecosystem
    "RUSTSEC-2024-0436",  # paste crate unmaintained - used by networking crates
]

# Database path for security advisories
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

[bans]
# Allow multiple versions for now - common in complex dependency trees
multiple-versions = "allow"

# Don't ban any specific crates for now
deny = []

# Skip checking these common crates that often have multiple versions
skip = [
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_msvc" },
    { name = "yamux" },
    { name = "syn" },
    { name = "proc-macro2" },
    { name = "quote" },
    { name = "unicode-ident" },
]

skip-tree = []

[sources]
# Allow all standard sources
unknown-registry = "allow" 
unknown-git = "allow"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []