apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paradigm-core
  namespace: paradigm
  labels:
    app: paradigm-core
    component: blockchain-node
spec:
  serviceName: paradigm-core-headless
  replicas: 3
  selector:
    matchLabels:
      app: paradigm-core
  template:
    metadata:
      labels:
        app: paradigm-core
        component: blockchain-node
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: paradigm-core
        image: paradigm/core:latest
        ports:
        - containerPort: 8545
          name: rpc
          protocol: TCP
        - containerPort: 8546
          name: websocket
          protocol: TCP
        - containerPort: 30303
          name: p2p
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: PARADIGM_NETWORK
          value: "mainnet"
        - name: PARADIGM_NODE_TYPE
          value: "full"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: config
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /health
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8545
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: paradigm-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast-ssd"
      resources:
        requests:
          storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: paradigm-core
  namespace: paradigm
  labels:
    app: paradigm-core
spec:
  type: ClusterIP
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: rpc
  - port: 8546
    targetPort: 8546
    protocol: TCP
    name: websocket
  selector:
    app: paradigm-core
---
apiVersion: v1
kind: Service
metadata:
  name: paradigm-core-headless
  namespace: paradigm
  labels:
    app: paradigm-core
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 30303
    targetPort: 30303
    protocol: TCP
    name: p2p
  selector:
    app: paradigm-core
---
apiVersion: v1
kind: Service
metadata:
  name: paradigm-core-lb
  namespace: paradigm
  labels:
    app: paradigm-core
spec:
  type: LoadBalancer
  ports:
  - port: 8545
    targetPort: 8545
    protocol: TCP
    name: rpc
  - port: 8546
    targetPort: 8546
    protocol: TCP
    name: websocket
  selector:
    app: paradigm-core