name: Docker Build Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/docker-test.yml'

permissions:
  contents: read
  packages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  docker-test:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Test build Core image (no push)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.core
        push: false
        tags: ghcr.io/aseio6668/paradigm/core:test
        
    - name: Test build and push Core image (with push)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile.core
        push: true
        tags: ghcr.io/aseio6668/paradigm/core:test
        cache-from: type=gha
        cache-to: type=gha,mode=max